public class Main {
    public static void main(String[] args) {
        System.out.println("Задача 1");
        var dog = 8.0;
        var cat = 3.6;
        var paper = 763789;
        System.out.println("dog = "+dog);
        System.out.println("cat = "+cat);
        System.out.println("paper = "+paper);
        System.out.println("Задача 2");
        dog = dog+4;
        cat = cat+4;
        paper = paper+4;
        System.out.println("new dog = "+dog+" new cat = "+cat+" new paper = "+paper);
        System.out.println("Задача 3");
        dog = dog-3.5;
        cat = cat-1.6;
        paper = paper-7639;
        System.out.println("dog "+dog);
        System.out.println("cat "+ cat);
        System.out.println("paper "+paper);
        System.out.println("Задача 4");
        var friend = 19;
        System.out.println("friend = "+friend);
        var friend2 = friend+2;
        System.out.println("friend = "+friend2);
        var friend3 = friend2/7;
        System.out.println("friend = "+friend3);
        System.out.println("Задача 5");
        var frog = 3.5;
        System.out.println("frog = "+frog);
        var frog2 = frog*10;
        System.out.println("frog = "+frog2);
        var frog3 = frog2/3.5;
        System.out.println("frog = "+frog3);
        var frog4 = frog3+4;
        System.out.println("frog = "+frog4);
        System.out.println("Задача 6");
        var weightBoxer1 = 78.2;
        var weightBoxer2 = 82.7;
        var result = weightBoxer1+weightBoxer2;
        System.out.println("общий вес боксеров "+result+" кг");
        var result2 = weightBoxer2-weightBoxer1;
        System.out.println("разница в весе боксеров "+result2+" кг");
        System.out.println("Задача 7");
        System.out.println("первый способ:");
        System.out.println("разница в весе боксеров "+result2+" кг");
        System.out.println("второй способ:");
        var result3 = weightBoxer2%weightBoxer1;
        System.out.println("разница в весе боксеров "+result3+" кг");
        System.out.println("Задача 8");
        System.out.println("Задача 8.1");
        var x = 640;
        var y = 8;
        var result4 = x/y;
        System.out.println("Всего работников в компании - "+result4+" человек");
        System.out.println("Задача 8.2");
        var result5 = result4+94;
        var result6 = x/result5;
        System.out.println("Если в компании работает "+result5+" человек, то всего "+result6+" часов работы может быть поделено между сотрудниками");
    }
}